"""项目常量和配置"""
from __future__ import annotations

from pathlib import Path

INTERSECTION_ORDER = tuple(f"J{i:02d}" for i in range(1, 31))
INTERSECTION_COUNT = len(INTERSECTION_ORDER)
FEATURES_PER_INTERSECTION = 22
STATE_DIMENSION = INTERSECTION_COUNT * FEATURES_PER_INTERSECTION
ACTION_COUNT_PER_INTERSECTION = 4
ACTION_NAMES = ("NS_Straight", "NS_Left", "EW_Straight", "EW_Left")
DIRECTIONS = ("N", "S", "E", "W")
MIN_GREEN_SECONDS = 15
YELLOW_TRANSITION_SECONDS = 3

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SUMO_FILES_DIR = PROJECT_ROOT / "sumo_files"
DOCS_DIR = PROJECT_ROOT / "docs"
SCRIPTS_DIR = PROJECT_ROOT / "scripts"
DATA_DIR = PROJECT_ROOT / "data"

DEFAULT_SUMO_CONFIG = SUMO_FILES_DIR / "xiongan.sumocfg"
DEFAULT_NET_FILE = SUMO_FILES_DIR / "xiongan.net.xml"
DEFAULT_ROU_FILE = SUMO_FILES_DIR / "xiongan.rou.xml"

STATE_LAYOUT_VERSION = "v1-30x22"
REWARD_VERSION = "v3"
API_VERSION = "v1"
